---
title: "bodyfat"
author: "gp1"
date: "2023/10/10"
output:
  rmdformats::readthedown:  
    code_folding: hide # hide
    self_contained: true
    thumbnails: false
    lightbox: false
    toc_depth: 2
    number_sections: true    
    toc_float:
     collapsed: true
     smooth_scroll: true    
---

```{r knitr_init, echo=FALSE, warning=FALSE, results="asis"}
library(knitr)
library(rmdformats)
library(ggplot2)
## Global options
options(max.print = "75")
opts_chunk$set(cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
opts_knit$set(width = 75)
```


## data cleaning
```{r}
df <- read.csv("BodyFat.csv")
head(df)
#summary(df)

#Brozek formula: BF=(4.57/ρ − 4.142) × 100[14]

# df[182,]$BODYFAT = -3.611687

#Siri formula is: BF=(4.95/ρ − 4.50) × 100[15]

# df[182,]$BODYFAT = -2.079881

# negative bodyfat so simply delete / or use mice ? as a NA

hist(df$WEIGHT)

center1 <- round((4.57/df$DENSITY)-4.142,3)*100
sum((df$BODYFAT<center1+1) & (df$BODYFAT>center1-1))
density_out_ind <- which(((df$BODYFAT<center1+1) & (df$BODYFAT>center1-1))==F)
density_out_ind


center2 <- round((df$WEIGHT/df$HEIGHT^2)*703,3)
sum((df$ADIPOSITY<center2+1) & (df$ADIPOSITY>center2-1))
bmi_out_ind <- which(((df$ADIPOSITY<center2+1) & (df$ADIPOSITY>center2-1))==F)
bmi_out_ind

outliers<- read.csv("BodyFat.csv")

outliers$IDNO <- NULL
z_score <- scale(outliers)
row_z_score <- rowSums(z_score^2)
outlier <- row_z_scores > 45
outliers$Status <- ifelse(outliers "Outlier", "Normal")
outliers <- outliers[, c(1, ncol(outliers), 2:(ncol(outliers)-1))]
```



## models

## cross validate and pick a model

## verify the model(assumption)

## blabla








